### ISSUE TITLE
flow start over after finish

### ISSUE THREAD

**Issue by gseffy** [openscore/score#23]
I get this exception in the log file:
java.lang.RuntimeException: Failed to serialize execution plan. Error:

**Comment by orius123** [comment]
can you please add the whole exception?

**Comment by gseffy** [comment]
2015-03-02 18:17:35:427 2435613 [WorkerExecutionThread-1_101600008] ERROR org.openscore.worker.management.services.SimpleExecutionRunnable  - Error during execution!!!
java.lang.RuntimeException: Failed to serialize execution plan. Error: 
	at org.openscore.engine.queue.entities.ExecutionMessageConverter.objToBytes(ExecutionMessageConverter.java:72)
	at org.openscore.engine.queue.entities.ExecutionMessageConverter.createPayload(ExecutionMessageConverter.java:36)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.createTerminatedExecutionMessage(SimpleExecutionRunnable.java:323)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.isExecutionTerminating(SimpleExecutionRunnable.java:393)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.shouldStop(SimpleExecutionRunnable.java:163)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.executeRegularStep(SimpleExecutionRunnable.java:149)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.run(SimpleExecutionRunnable.java:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.openscore.worker.management.services.WorkerThreadFactory$1.run(WorkerThreadFactory.java:33)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.NotSerializableException: org.python.core.PyUnicode$1
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.writeObject(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at java.util.HashMap.internalWriteEntries(Unknown Source)
	at java.util.HashMap.writeObject(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at java.util.HashMap.internalWriteEntries(Unknown Source)
	at java.util.HashMap.writeObject(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at org.openscore.engine.queue.entities.ExecutionMessageConverter.objToBytes(ExecutionMessageConverter.java:66)
	... 12 more
2015-03-02 18:17:35:434 2435620 [scoreWorkerScheduler-2] ERROR org.openscore.worker.management.services.RetryTemplate  - Try #1 failed on: 
java.lang.NullPointerException
	at org.openscore.engine.queue.entities.ExecutionMessageConverter.extractExecution(ExecutionMessageConverter.java:32)
	at org.openscore.engine.queue.services.QueueListenerImpl.extractExecution(QueueListenerImpl.java:132)
	at org.openscore.engine.queue.services.QueueListenerImpl.deleteExecutionStateObjects(QueueListenerImpl.java:190)
	at org.openscore.engine.queue.services.QueueListenerImpl.onFailed(QueueListenerImpl.java:141)
	at org.openscore.engine.queue.services.ExecutionQueueServiceImpl.enqueue(ExecutionQueueServiceImpl.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy74.enqueue(Unknown Source)
	at org.openscore.engine.queue.services.QueueDispatcherServiceImpl.dispatch(QueueDispatcherServiceImpl.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy88.dispatch(Unknown Source)
	at org.openscore.orchestrator.services.OrchestratorDispatcherServiceImpl$1.handle(OrchestratorDispatcherServiceImpl.java:86)
	at org.openscore.orchestrator.services.OrchestratorDispatcherServiceImpl.dispatch(OrchestratorDispatcherServiceImpl.java:109)
	at org.openscore.orchestrator.services.OrchestratorDispatcherServiceImpl.dispatch(OrchestratorDispatcherServiceImpl.java:82)
	at org.openscore.orchestrator.services.OrchestratorDispatcherServiceImpl.dispatch(OrchestratorDispatcherServiceImpl.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy97.dispatch(Unknown Source)
	at org.openscore.worker.management.services.OutboundBufferImpl$1.tryOnce(OutboundBufferImpl.java:187)
	at org.openscore.worker.management.services.RetryTemplate.retry(RetryTemplate.java:36)
	at org.openscore.worker.management.services.OutboundBufferImpl.drainBulk(OutboundBufferImpl.java:182)
	at org.openscore.worker.management.services.OutboundBufferImpl.drainInternal(OutboundBufferImpl.java:155)
	at org.openscore.worker.management.services.OutboundBufferImpl.drain(OutboundBufferImpl.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2015-03-02 18:17:40:443 2440629 [scoreWorkerScheduler-2] ERROR org.openscore.worker.management.services.RetryTemplate  - Try #2 failed on: 
java.lang.NullPointerException

**Comment by meirwah** [comment]
This seems to be blocking PR #30 in slang-content repo...

**Comment by orius123** [comment]
I think it is related to problem with serialization of Jython objects. and then recovery happens..
looking into it.

**Comment by meirwah** [comment]
@gseffy  can you write which flow you run that causes this?

**Comment by gseffy** [comment]
consul/report_kv.sl
but I think it happens when the flow last task is python task...

**Comment by meirwah** [comment]
adding @Bonczidai , which sees similar issue in his Deis flow...

**Comment by orius123** [comment]
ok, so it seems that the issue is with upgrading jython to the latest beta..
still validating..

**Comment by meirwah** [comment]
@orius123 did you downgrade the Jython version?

**Comment by orius123** [comment]
now i did.
it solves most of those exceptions.
in loops we still have this exaptions though, opended openscore/score-language#137 to handle it.
